language: cpp
sudo: false
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab3-postfix
  - make -j
  - cd ./bin/
  - ./sample_postfix
notifications:
  email: false
