language: cpp
sudo: false
compiler:
  - gcc
  - clang
before_script:
  - bash ./scripts/check-whitespace.sh
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Сысоев
  - make -j
  - cd ./bin/
  - ./sample_postfix
notifications:
  email: false
